const products = [
  {
    _id: '1',
    name: 'Vintage Emerald Green Sofa',
    image: '/images/vintageemeraldgreensofa.jpg',
    description: '',
    brand: 'Mid Mod',
    category: 'Furniture',
    price: 1049.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Mid Century Modern Leather Sofa',
    image: '/images/vintageleathersofa.jpg',
    description: '',
    brand: 'Article',
    category: 'Furniture',
    price: 1599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Mid Century Modern Chair',
    image: '/images/midcenturymodernchair.jpg',
    description: '',
    brand: 'Mid Mod',
    category: 'Furniture',
    price: 74.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Mid Century Modern High Chair',
    image: '/images/midcenturymodernhighchair.jpg',
    description: '',
    brand: 'Mid Mod',
    category: 'Furniture',
    price: 99.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Danish Teak Armoire',
    image: '/images/danishteakarmoire.jpg',
    description: '',
    brand: 'Mid Mod',
    category: 'Furniture',
    price: 1549.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Danish Teak Chair',
    image: '/images/danishteakchair.jpg',
    description: '',
    brand: 'Mid Mod',
    category: 'Furniture',
    price: 349.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
